# Generated by Django 4.0.4 on 2022-04-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_candidates_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='reference_id',
        ),
    ]
